name: Deploy

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build crate
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build site
      run: cd example && ../target/debug/rustman build
